### ISSUE TITLE
ip_address not ip

### ISSUE THREAD

**Issue by ChrisQ13** [mcafee/RTS-Queries#2]
In queries like: 
HostInfo connection_status, hostname, ip, platform 
I get the error "ip is not an output field for collector HostInfo"
This query is fixed by using ip_address instead of ip

**Comment by dfirence** [comment]
Hi Chris,

Thank you for noting this typo.  We have made the initial changes in the README and are working on the others!

Appreciate your feedback!

**Comment by dfirence** [comment]
Scan complete, typo existed in the README section, fixed:

closing this issue.
