### ISSUE TITLE
Small typo in following

### ISSUE THREAD

**Issue by ChrisQ13** [mcafee/RTS-Queries#3]
InstalledUpdates hotfix_id, install_date, installed_by, description     
    WHERE InstalledUpdates install_date after "2018-03-01"
        AND InstalledUpdates hotfix_id ends with "KB4012212"
            OR InstalledUpdates.hotfix_id ends with "KB4012215"
            OR InstalledUpdates hotfix_id ends with "KB4012218"
            OR InstalledUpdates hotfix_id ends with "KB4015549"

This line:
OR InstalledUpdates.hotfix_id ends with "KB4012215"

has InstalledUpdates.hotfix but should be InstalledUpdates hotfix

**Comment by dfirence** [comment]
Hi Chris,

Thank you for spotting this small typo.  It has been fixed now and can be referenced in this commit.

```
https://github.com/mcafee/RTS-Queries/commit/f6cb4a052bc06ab8ab387f78c52c92113b4ea2b0
```
